FORMAT: 1A

# Docking API

The API of getting information from the `SimpleServer.py` server.

# Group Users

## Users Collection [/users{?role,name}]

### List All Users [GET]

* Parameters

    * role: `manager` (string, optional) - Role of the user in the system.

    * name: `John` (string, optional) - Name of the user.

* Response 200 (application/json)

        [
            {
                "name": "John Liu",
                "id": "1",
                "role": "sales"
            },
            {
                "name": "Jordan Lin",
                "id": "2",
                "role": "manager"
            }
        ]

## User [/users/{userId}]

* Parameters

    * userId: `1` (string) - The ID of the user

### View User Detail [GET]

* Response 200 (application/json)

        {
            "name": "John Liu",
            "id": "1",
            "role": "sales"
        }

* Response 404 (application/json)

        {
            "type": "Not Found"
            "message": "User ID cannot be found."
        }

# Group Customers

## Customers [/customers{?name,salesId}]

### List All Customers [GET]

* Parameters

    * name: `Andy` (string, optional) - Name of the customer

    * salesId: `1` (string, optional) - Search customers by the responsible salesperson's id

* Response 200 (application/json)

        [
            {
                "name": "Andy Ziemmer",
                "id": "1",
                "salesId": "1",
            },
            {
                "name": "Nick Omar",
                "id": "2",
                "salesId": "2",
            }
        ]

## Customer [/customers/{customerId}]

* Parameters

    * customerId: `1` (string) - The id of the customer

### View Customer Detail [GET]

* Response 200 (application/json)

        {
            "name": "Andy Ziemmer",
            "id": "1",
            "customerId": "1",
        }

* Response 404 (application/json)

        {
            "type": "Not Found"
            "message": "Customer ID cannot be found."
        }
